name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Run Qodana
        uses: JetBrains/qodana-action@v2024.3
        with:
          linter: jetbrains/qodana-jvm:2024.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
